### ISSUE TITLE
Using environment variables results in errors?

### ISSUE THREAD

**Issue by IPWright83** [jwalton/gh-ecr-push#4]
I've been fighting with this action for a few hours, after having it working, then accidentally breaking it. Be interested in your thoughts/any way of debugging this.

So I've got a working step in my workflow that looks like this:

```
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{secrets.AWS_ECR_ACCESS_KEY_ID_DEV}}
          secret-access-key: ${{secrets.AWS_ECR_SECRET_ACCESS_KEY_DEV}}
          region: eu-west-1
          image: strapi-cms:latest
```

What I'm trying to do, is to swap the AWS_ECR_ACCESS_KEY_ID_DEV and AWS_ECR_SECRET_ACCESS_KEY_DEV secrets for different branches. We do this by copying secrets into environment variables and passing them in:

```
      - name: Echo test
        run: |
          echo $AWS_ACCOUNT_ID
          echo $AWS_ECR_ACCESS_KEY_ID
          echo $AWS_ECR_SECRET_ACCESS_KEY

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: $AWS_ECR_ACCESS_KEY_ID
          secret-access-key: $AWS_ECR_SECRET_ACCESS_KEY
          region: eu-west-1
          image: strapi-cms:latest
```

This however fails with 
> An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.

Notice the additional echo step, that seems to be working (manually redacted first 2 lines) - although obviously I can't see the `AWS_ECR_SECRET_ACCESS_KEY` value in the console.

![image](https://user-images.githubusercontent.com/1374775/86926349-d9cafc00-c129-11ea-9934-7fbefda74253.png)

Do you know what I might be missing here? Or how I might be able to debug this action?

**Comment by dochne** [comment]
I had a similar issue, instead of using the ENV syntax of `$AWS_ECR_ACCESS_KEY_ID` you want to write something more like this:

```
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          secret-access-key:  ${{ env.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-1
          image:  strapi-cms:latest
```
