### ISSUE TITLE
Suport multiple tags

### ISSUE THREAD

**Issue by TiagoGouvea** [jwalton/gh-ecr-push#7]
It would be good to support multiple tags? Some like:

```
- run: docker build --tag my-image .
- name: Push to ECR
  id: ecr
  uses: jwalton/gh-ecr-push@v1
  with:
    access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    region: us-east-1
    local-image: my-image
    image: my-image:dev-${{ github.sha }}, my-image:latest
```

If it is, I can write it and open a PR.
