### ISSUE TITLE
How to push image from a child directory inside monorepo

### ISSUE THREAD

**Issue by mocon** [jwalton/gh-ecr-push#89]
Hello @jwalton and thank you for this awesome action. I'm trying to push an image from the `apps/trpc-express` directory of my Nx monorepo, and wondering if there's a way to switch the context to that directory:

```yaml
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"
      - name: Confirm git commit SHA output
        run: echo ${{ steps.vars.outputs.short_sha }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: trpc-express
          IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
        run: |
          cd apps/trpc-express
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      - name: Push image to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-west-1
          image: trpc-express:${{ steps.vars.outputs.short_sha }}
```

Thanks!
